theme: jekyll-theme-hacker

description: Cloud adventures by Casper

logo: images/casper.png
author: Casper Dijkstra
github_username: cdijkstra

giscus:
  repo: "cdijkstra/Blog"

collections:
  tags:
    output: true
    permalink: tags/:path/